# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15uM70caDBtpv8-G2TeMlBznAzRDQH_FV
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

iris = load_iris()
X = iris.data
y = iris.target

y = to_categorical(y)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = Sequential()
model.add(Dense(16, activation='relu', input_shape=(4,)))
model.add(Dense(12, activation='relu'))
model.add(Dense(3, activation='softmax'))

"""# **Sequential**

Sequential() is a model in Keras where layers are added one after another in sequence.

Input Layer

     ↓
Hidden Layer

     ↓
Hidden Layer

     ↓
Output Layer
"""

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=8 # 8 samples processed at one time.
)

loss, accuracy = model.evaluate(X_test, y_test)

print("Accuracy:", accuracy)

prediction = model.predict(X_test)

print(prediction[0])

import numpy as np

predicted_class = np.argmax(prediction[0])

class_names = iris.target_names

print("Predicted Class:", class_names[predicted_class])

# ==============================
# Show Actual Class vs Predicted Class
# ==============================

# Predict all test data
predictions = model.predict(X_test)

# Get class names
class_names = iris.target_names

print("\n========= ACTUAL vs PREDICTED =========\n")

for i in range(10):

    # Predicted class index
    predicted_index = np.argmax(predictions[i])

    # Actual class index
    actual_index = np.argmax(y_test[i])

    # Convert index into class name
    predicted_class = class_names[predicted_index]
    actual_class = class_names[actual_index]

    # Print result
    print(f"Sample {i+1}")
    print("Actual Class    :", actual_class)
    print("Predicted Class :", predicted_class)
    print("-" * 40)

"""# **Important Terms**

| Term                | Meaning                 |
| ------------------- | ----------------------- |
| Neuron              | Small processing unit   |
| Weight              | Importance of input     |
| Bias                | Extra adjustment        |
| Activation Function | Decides output          |
| Epoch               | One full training cycle |
| Loss                | Error value             |
| Optimizer           | Reduces error           |
"""

