# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Ok_oSlKz_Wnw9fMo4O_nWfHo3mis-e4
"""

# Neural network learning process
# Input -> Weights -> Bias -> output -> Error ->update

import numpy as np

#Input data
X = np.array([1,2,3,4])

#output data
y = np.array([2,4,6,8])

# initial weights and bias
weight = 0.5
bias = 0.0

#learning rate
lr = 0.01

# Training

for epoch in range(1000):

  #prediction
  y_pred = weight * X + bias

  #error
  error = y-y_pred

  #update weight and bias
  weight = weight + lr * np.mean(error * X)
  bias = bias + lr * np.mean(error )

#Final prediction
print("learned weight:", round(weight,2))
print("learned bias:", round(bias,2))

#Test

test = 5
prediction  =  weight * test + bias
print(f"prediction for{test} is", round(prediction , 2))

